# These are supported funding model platforms
github: [fabriciobastian]
custom: ["https://www.paypal.com/donate/?business=VJKKWDQV7A8DU&no_recurring=0&item_name=Buy+me+a+coffee%21&currency_code=USD"]
